# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 13:47
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=120)),
                ('图片', models.FileField(blank=True, null=True, upload_to=blog.models.upload_location)),
                ('内容', models.TextField()),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('发布时间', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
