# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='内容',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='update',
            new_name='更新时间',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='标题',
        ),
    ]
