# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161109_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='图片',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
